# Generated by Django 3.2.4 on 2021-07-18 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(help_text='Playlist ID', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Playlist title', max_length=100)),
                ('desc', models.TextField(blank=True, help_text='Playlist description', null=True)),
                ('user_id', models.CharField(help_text='User ID', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(help_text='Track ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Track name', max_length=100)),
                ('artist', models.CharField(help_text='Track artist', max_length=100)),
                ('album', models.CharField(help_text='Track album', max_length=100)),
                ('image', models.TextField(help_text='Track image')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.playlist')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.track')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(through='playlist.PlaylistTrack', to='playlist.Track'),
        ),
    ]
