# Generated by Django 3.2.4 on 2021-07-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_auto_20210719_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlisttrack',
            old_name='pid',
            new_name='playlist',
        ),
        migrations.RenameField(
            model_name='playlisttrack',
            old_name='tid',
            new_name='track',
        ),
        migrations.AddField(
            model_name='playlist',
            name='public',
            field=models.BooleanField(default=True, help_text='Playlist public'),
        ),
    ]
