# Generated by Django 3.2.4 on 2021-07-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_auto_20210719_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='category', to='playlist.Category'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(blank=True, null=True, related_name='track', through='playlist.PlaylistTrack', to='playlist.Track'),
        ),
    ]
