# Generated by Django 3.2.4 on 2021-07-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_auto_20210720_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedItems',
            fields=[
                ('id', models.CharField(help_text='spotify track id', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Track name', max_length=100)),
                ('artist', models.CharField(help_text='Track artist', max_length=100)),
                ('album', models.CharField(help_text='Track album', max_length=100)),
                ('image', models.TextField(help_text='Track image')),
                ('preview_url', models.TextField(help_text='preview_url')),
                ('danceability', models.FloatField(help_text='audio features danceability')),
                ('energy', models.FloatField(help_text='audio features energy')),
                ('key', models.FloatField(help_text='audio features key')),
                ('loudness', models.FloatField(help_text='audio features loudness')),
                ('mode', models.FloatField(help_text='audio features mode')),
                ('speechiness', models.FloatField(help_text='audio features speechiness')),
                ('acousticness', models.FloatField(help_text='audio features acousticness')),
                ('instrumentalness', models.FloatField(help_text='audio features instrumentalness')),
                ('liveness', models.FloatField(help_text='audio features liveness')),
                ('valence', models.FloatField(help_text='audio features valence')),
                ('tempo', models.FloatField(help_text='audio features tempo')),
                ('duration_ms', models.FloatField(help_text='audio features duration_ms')),
                ('time_signature', models.FloatField(help_text='audio features time_signature')),
            ],
        ),
        migrations.AlterField(
            model_name='playlist',
            name='category',
            field=models.ManyToManyField(related_name='category', to='playlist.Category'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(related_name='track', through='playlist.PlaylistTrack', to='playlist.Track'),
        ),
    ]
