# Generated by Django 3.2.4 on 2021-07-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0007_playlist_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='preview_url',
            field=models.TextField(blank=True, help_text='Track preview_url', null=True),
        ),
    ]
