# Generated by Django 3.2.4 on 2021-07-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listid', models.CharField(max_length=64, verbose_name='플레이리스트id')),
                ('song', models.CharField(max_length=64, verbose_name='노래명')),
                ('registered', models.DateTimeField(auto_now_add=True, verbose_name='등록')),
            ],
        ),
        migrations.CreateModel(
            name='UserPlaylist',
            fields=[
                ('listid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64, verbose_name='사용자명')),
                ('playlist', models.CharField(max_length=64, verbose_name='플레이리스트명')),
            ],
        ),
    ]
