# Generated by Django 3.2.4 on 2021-07-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplaylist',
            name='desc',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='listid',
            field=models.IntegerField(verbose_name='플레이리스트id'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='song',
            field=models.IntegerField(verbose_name='노래번호'),
        ),
    ]
