# Generated by Django 3.2.4 on 2021-07-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20210714_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='제목')),
                ('artist', models.CharField(max_length=64, verbose_name='가수')),
                ('album', models.CharField(max_length=64, verbose_name='앨범명')),
                ('data', models.CharField(max_length=64, verbose_name='출시일')),
                ('cover', models.CharField(max_length=64, verbose_name='앨범커버')),
            ],
        ),
    ]
